### ISSUE TITLE
AG95

### ISSUE THREAD

**Issue by chiawenwang** [Hymwgk/go_grasp#1]
请问你在仿真中用了AG95吗？他的urdf模型是否在有链接吗？谢谢！

**Comment by wmhch** [comment]
请问你解决这个问题了吗，我也遇到同样的问题

**Comment by chiawenwang** [comment]
> 请问你解决这个问题了吗，我也遇到同样的问题

后面就没有继续做这个仿真了，直接做实物了，可以问问厂家有没有urdf模型
